rename from venus-cluster to damocles / 改名成damocels
ipfs-force-community/damocles-docs pull request #27
Opened 2023-09-05 07:59 UTC by elvin-du

2023-09-06 03:24 UTC, Fatman13 requested changes

2023-09-06 03:24 UTC, Fatman13 commented on docs/zh/intro/getting-started.md
> +   git clone https://github.com/ipfs-force-community/damocles.git
这个文件应该可以删除，不需要了。正确的那个在 operation 文件夹下面，我看展示的是正确的。

2023-09-06 03:24 UTC, Fatman13 commented on docs/.vuepress/config.js
> +        '10.damocles-worker%E4%BB%BB%E5%8A%A1%E7%AE%A1%E7%90%86.md': ['task-management.md', 'worker 任务管理'],
这个 damocles 仓库自己改名字之前还不能改，否则找不到那个文件了。这个主要是文档框架内部的，外面看文档的，看不到这个名字。

2023-09-06 03:24 UTC, Fatman13 commented on docs/.vuepress/config.js
> +                                U('https://github.com/ipfs-force-community/damocles/blob/main/docs/zh/10.damocles-worker%E4%BB%BB%E5%8A%A1%E7%AE%A1%E7%90%86.md'),
理由同上，得和这个[文件夹](https://github.com/ipfs-force-community/damocles/tree/main/docs/zh)里面的文件名称一致。

2023-09-25 07:59 UTC, 0x5459 commented on docs/.vuepress/config.js
> +        '10.damocles-worker%E4%BB%BB%E5%8A%A1%E7%AE%A1%E7%90%86.md': ['task-management.md', 'worker 任务管理'],
嗯，这还是挺尴尬的，damocles 仓库那边的文档名字忘记改了。等会我改一下

https://github.com/ipfs-force-community/damocles/blob/main/docs/zh/10.venus-worker%E4%BB%BB%E5%8A%A1%E7%AE%A1%E7%90%86.md

2023-10-12 03:06 UTC, 0x5459 commented on docs/.vuepress/config.js
> +        '10.damocles-worker%E4%BB%BB%E5%8A%A1%E7%AE%A1%E7%90%86.md': ['task-management.md', 'worker 任务管理'],
https://github.com/ipfs-force-community/damocles/pull/986

2023-10-12 03:09 UTC, 0x5459 commented
@Fatman13  https://github.com/ipfs-force-community/damocles/pull/986 merged!

2023-10-25 02:00 UTC, Fatman13 approved these changes
LGTM

2023-10-25 02:00 UTC, merged